[package]
name = "cli"
description = "ğŸº The high-performance, type-safe and modern TypeScript web framework written in Rust."
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kito"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
async-trait = "0.1.89"
clap = { version = "4.5.47", features = ["derive"] }
paste = "1.0.15"
tokio = { version = "1.47.1", features = ["full"] }
